### PR TITLE
Add pycodestyle linting workflow

### PR DESCRIPTION
**Pull request by GuyOmer**
This adds a workflow for linting all added code.

Notes:
- This checks the entire project, it is not  strict to the modified files. So first few PRs will suffer from unrelated code linting warnings.
- Currently, I am using the default pycodestyle settings. We might want to modify them according to this project styling.
- This should not be deployed to production server (obviously)

### CODE REVIEW

**Comment by stavlocker** [comment]
@GuyOmer looking at the output above, we should probably create a custom linting file so we could for example increase the line limit from 79 characters to 120.

And ignore migration files.

Plus, maybe we could only lint files changed?

**Comment by GuyOmer** [comment]
> @GuyOmer looking at the output above, we should probably create a custom linting file so we could for example increase the line limit from 79 characters to 120.
> 
> And ignore migration files.
> 
> Plus, maybe we could only lint files changed?

Agree, added custom log lines + excluding the migrations directory.

**Comment by stavlocker** [comment]
* The output of the bot contains no whitespace and is very difficult to read. Is there any way to fix this?
* Ignore manage.py too 
* Isn't this supposed to be merged into develop and only then into master?
* Does this mean that we have to fix all the linting problems in the project before merging this issue?

**Comment by GuyOmer** [comment]
test
    test

**Comment by GuyOmer** [comment]
> * The output of the bot contains no whitespace and is very difficult to read. Is there any way to fix this?
> * Ignore manage.py too
> * Isn't this supposed to be merged into develop and only then into master?
> * Does this mean that we have to fix all the linting problems in the project before merging this issue?

1. whitespace issue is fixed now :)
2. Added mange.py to exclude list.
3. You are right - it should be merged into develop (changed it)
4. Sort of... The other option is having every PR with linting warnings until someoby fixes them.

**Comment by stavlocker** [comment]
@GuyOmer Looks great!

I'm not merging this yet until we fix all the linting comments so every pull request won't appear faulty.

Some files still need to be ignored (like setup.py since we have to run a function before importing, Django stuff) - I'll give a full list when I finish fixing all linting comments.

**Comment by GuyOmer** [comment]
@stavlocker Changed things as we disucssed.
I also added posting a comment if the workflow itself breaks.

Its quite fragile because pycodestyle outputs un-sanitized output (which JSON dislikes). But I believe I covered most of the these cases.

**Pull request merged**
